### ISSUE TITLE
Is this library available on rubygems?

### ISSUE THREAD

**Issue by beedub** [fac/hestia#2]
I can't find it on rubygems.org

**Comment by caius** [comment]
Hey,

I hadn't pushed it to rubygems yet, no, so you wouldn't have been able to find it there. (We've been pulling it in as a git repo to our rails app using Bundler.)

I've pushed it up now as v0.0.2 though, so you'll be able to `gem install hestia` and it's at https://rubygems.org/gems/hestia on the website.

Thanks!
